/* config.h. Generated by cmake from config.h.cmake */

/*
 * Indicates the byte order of your target system
 * 1 if little-endian, 2 if big-endian.
 */
#define   SYSTEM_BYTEORDER 1

/* Defined if your compiler supports some byte swap functions */
#define   HAVE_GCC_BYTESWAP_16 1
#define   HAVE_GCC_BYTESWAP_32 1
#define   HAVE_GCC_BYTESWAP_64 1

/* Defined if your compiler supports codecvt */
#define   HAVE_STD_CODECVT 1

/*
 * Defined if your compiler supports some atomic operations
 */
#define   HAVE_GCC_ATOMIC 1

/* Defined if your compiler supports some safer version of sprintf */
#define   HAVE_SNPRINTF 1

/* Defined if you have libz */
#define   HAVE_ZLIB 1
